# Change these first
owner: joshuaepstein # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Development Website
    url: https://dev.joshepstein.co.uk
    icon: https://dev.joshepstein.co.uk/img/favicon.png
  - name: JoshuaEpstein
    url: https://joshepstein.co.uk
    icon: https://www.joshepstein.co.uk/img/white-logo.svg
  - name: JFS Tech
    url: https://jfstech.uk
    icon: https://jfstech.uk/logo.svg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.joshepstein.co.uk
  # baseUrl: /your-repo-name
  themeUrl: https://dev.joshepstein.co.uk/css/other/status/dark-custom-style.css
  logoUrl: https://dev.joshepstein.co.uk/img/colored-logo.svg
  favicon: https://dev.joshepstein.co.uk/img/favicon.png
  faviconSvg: https://dev.joshepstein.co.uk/img/favicon.svg
  name: JoshuaEpstein Status
  introTitle: "JoshuaEpstein Services"
  introMessage: Check if a JoshuaEpstein Service is up or down. You can report issues that you have with any services on the report page on the JoshuaEpstein Dev Website -> https://dev.joshepstein.co.uk/report/issue?ref=status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Development
      href: https://dev.joshepstein.co.uk
